## Rear_Left, MOTOR_6, DIAG_6
[stepper_x]
step_pin: PE2
dir_pin: PE3
enable_pin: !PD4
rotation_distance: 40
microsteps: 32
full_steps_per_rotation: 200  
endstop_pin: Ebb36:PB8 #tmc2240_stepper_x:virtual_endstop
position_min: 0
position_endstop: 324
position_max: 324
homing_speed: 50 #20   
homing_retract_dist: 0
homing_positive_dir: True

[tmc2240 stepper_x]
cs_pin: PE1
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 1
rref: 12000
#stealthchop_threshold: 99999
#diag0_pin: ^!PG14
#driver_SGT: 3     # -64 most sensitive - 63 least sensitive

[autotune_tmc stepper_x]
motor: moons-ms17hd6p420I-04
tuning_goal: performance

##REAR_RIGHT, MOTOR_1, DIAG_1
[stepper_y]
step_pin: PG0
dir_pin: PG1
enable_pin: !PF15
rotation_distance: 40
microsteps: 32
full_steps_per_rotation: 200  
endstop_pin: PG10 #tmc2240_stepper_y:virtual_endstop
position_min: 0
position_endstop: 293
position_max: 293
homing_speed: 50 #20  
homing_retract_dist: 0
#homing_positive_dir: True

[tmc2240 stepper_y]
cs_pin: PD11
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 1
rref: 12000
#stealthchop_threshold: 99999
#diag0_pin: ^!PG9
#driver_SGT: 4

[autotune_tmc stepper_y]
motor: moons-ms17hd6p420I-04
tuning_goal: performance

## FRONT_LEFT, MOTOR_2, DIAG_2
[stepper_z]
step_pin: PF11
dir_pin: PG3
enable_pin: !PG5
rotation_distance: 4    
microsteps: 32
endstop_pin: probe:z_virtual_endstop
position_max: 245
position_min: -2.5
homing_speed: 8.0 
second_homing_speed: 3
homing_retract_dist: 0

[tmc2240 stepper_z]
cs_pin: PC6
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 0.75
rref: 12000
#stealthchop_threshold: 99999

[autotune_tmc stepper_z]
motor: oukeda-ok42hc40-204a306n84
tuning_goal: performance

## REAR_CENTER, MOTOR_3
[stepper_z1]
step_pin: PG4
dir_pin: PC1
enable_pin: !PA0
rotation_distance: 4  
microsteps: 32

[tmc2240 stepper_z1]
cs_pin: PC7
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 0.75
rref: 12000
#stealthchop_threshold: 99999

[autotune_tmc stepper_z1]
motor: oukeda-ok42hc40-204a306n84
tuning_goal: performance

## FRONT_RIGHT, MOTOR_4
[stepper_z2]
step_pin: PF9
dir_pin: PF10
enable_pin: !PG2
rotation_distance: 4  
microsteps: 32

[tmc2240 stepper_z2]
cs_pin: PF2
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 0.75
rref: 12000
#stealthchop_threshold: 99999

[autotune_tmc stepper_z2]
motor: oukeda-ok42hc40-204a306n84
tuning_goal: performance

[extruder]
step_pin: PF0
dir_pin: PC13
enable_pin: !PF1
rotation_distance: 47.088
gear_ratio: 9:1
microsteps: 16
full_steps_per_rotation: 200
nozzle_diameter: 0.600
filament_diameter: 1.75
sensor_type: NTC 100K MGB18-104F39050L32
sensor_pin: Ebb36:PA3
heater_pin: Ebb36:PB13
min_temp: 10
max_temp: 350
max_power: 1.0
min_extrude_temp: 225
max_extrude_only_distance: 150
max_extrude_cross_section: 10
pressure_advance: 0.05
pressure_advance_smooth_time: 0.040
control: pid
pid_kp: 21.975
pid_ki: 1.409
pid_kd: 85.704

[tmc2240 extruder]
cs_pin: PE4
spi_speed: 500000
spi_software_sclk_pin: PA5
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
interpolate: True
run_current: 0.6
rref: 12000
#stealthchop_threshold: 99999
#driver_IHOLDDELAY: 8
#driver_IRUNDELAY: 2
#driver_TBL: 3
#driver_TOFF: 4
#driver_HEND: 3
#driver_HSTRT: 4
#driver_TPFD: 0
#driver_PWM_AUTOSCALE: True
#driver_PWM_AUTOGRAD: True
#driver_PWM_GRAD: 12
#driver_PWM_OFS: 40
#driver_PWM_REG: 15
#driver_PWM_LIM: 12
#driver_SGT: 30
#driver_SEMIN: 2
#driver_SEMAX: 8
#diag0_pin: PG13

[autotune_tmc extruder]
motor: ldo-36sth20-1004ahg-9T
tuning_goal: performance